services:
  - type: web
    name: flask-site
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn src.main:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
databases:
  - name: postgres
    plan: free
    envVarName: DATABASE_URL
